# This is a local kafka cluster for working on developing workloads 
# for the kafka problem 
version: '2'

services:
  kafka-1:
    image: docker.io/bitnamilegacy/kafka:3.7.0
    container_name: kafka-1
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@10.0.0.15:9094,2@10.0.0.20:9094,3@10.0.0.25:9094"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_KRAFT_CLUSTER_ID: kafka
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://10.0.0.15:9092,EXTERNAL://localhost:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_NUM_PARTITIONS: 10
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 3
      JAVA_DEBUG_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n"
    ports:
      - 9092:9093
    networks: 
      cluster-net:
        ipv4_address: 10.0.0.15
    user: root

  kafka-2:
    image: docker.io/bitnamilegacy/kafka:3.7.0
    container_name: kafka-2
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@10.0.0.15:9094,2@10.0.0.20:9094,3@10.0.0.25:9094"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_KRAFT_CLUSTER_ID: kafka
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://10.0.0.20:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_NUM_PARTITIONS: 10
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 3
      JAVA_DEBUG_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n"
    ports:
      - 9093:9093
    networks:
      cluster-net:
        ipv4_address: 10.0.0.20
    user: root
    depends_on:
      - kafka-1

  kafka-3:
    image: docker.io/bitnamilegacy/kafka:3.7.0
    container_name: kafka-3
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@10.0.0.15:9094,2@10.0.0.20:9094,3@10.0.0.25:9094"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_KRAFT_CLUSTER_ID: kafka
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://10.0.0.25:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_NUM_PARTITIONS: 10
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 3
      JAVA_DEBUG_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n"
    ports:
      - 9094:9093
    networks:
      cluster-net:
        ipv4_address: 10.0.0.25
    user: root
    depends_on:
      - kafka-2
  workload:
    image: localhost/antithesis-kafka-workload:latest
    container_name: workload
    volumes:
      - ./workload-config.json:/app/workload-config.json
    networks:
      - cluster-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

networks:
  cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24